#!/bin/bash
# Defaults
DIR_SUPPLIES="$(dirname "$0")/supplies"
EXT_SUPPLIES="box"
LINK_TLD="com"

source "./labby.conf"

usage() {
cat <<'EOF'
Lab Supply Tracker
Usage:
  labby <text> - find the specified search text (case insensitive)
  labby w <id> - open web page for specified product id
  labby a <box> <id> - add information about an item to the specified box
EOF
}

getDigikeyLink() {
  echo "http://www.digikey.${LINK_TLD}/product-search/en?keywords=${1#DK-}"
}
getEbayItemLink() {
  echo "http://www.ebay.${LINK_TLD}/itm/${1#EB-}"
}
getFarnellLink() {
  if [ "${LINK_TLD}" == "com" ]; then
    echo "http://farnell.com/jsp/search/productdetail.jsp?SKU=${1#FL-}"
  elif [ "${LINK_TLD}" == "co.uk" ]; then
    echo "http://uk.farnell.com/jsp/search/productdetail.jsp?SKU=${1#FL-}"
  else
    echo "http://${LINK_TLD}.farnell.com/jsp/search/productdetail.jsp?SKU=${1#FL-}"
  fi
}
getMouserLink() {
  if [ "${LINK_TLD}" == "com" ]; then
    echo "http://mouser.com/ProductDetail/${1#MR-}"
  elif [ "${LINK_TLD}" == "co.uk" ]; then
    echo "http://uk.mouser.com/ProductDetail/${1#MR-}"
  else
    echo "http://${LINK_TLD}.mouser.com/ProductDetail/${1#MR-}"
  fi
}

openPage() {
  case "$1" in
    DK-*) s=$(getDigikeyLink ${1}) ;;
    EB-*) s=$(getEbayItemLink ${1}) ;;
    FL-*) s=$(getFarnellLink ${1}) ;;
    MR-*) s=$(getMouserLink ${1}) ;;
    # use DigiKey if there is no supplier prefix
    *)    s=$(getDigikeyLink ${1}) ;;
  esac
  osOpen $s  # opens a web browser window, since $s is a URL
}

osOpen() {
  if [ "${OS+$OS}" == "Windows_NT" ]; then
    start $1
  else
    open $1
  fi
}

addItem() {
  case "$1" in
    "") echo "Usage: labby a <box> <supplier-partid> ?<optional-notes>?"
        return ;;
  esac
  if [ ! -f "$DIR_SUPPLIES/$1.$EXT_SUPPLIES" ]; then
    echo "'$1' is not an existing box, you need to create it first as '$DIR_SUPPLIES/$1.$EXT_SUPPLIES'"
    return
  fi
  case "$2" in
    DK-*) ;;
    *) echo "Please specify a supplier and part id, e.g. 'DK-1N5239BFSCT-ND'"
       return ;;
  esac
  echo "whoops, this feature is not working yet..."
}

case "$1" in
  "") usage ;;
  w)  openPage $2 ;;
  a)  addItem $2 $3 ;;
  *)  cd "$DIR_SUPPLIES"; grep -i --exclude=*.txt "$*" * | sed -e "s/	/  /g" -e "s/.$EXT_SUPPLIES:/	/" ;;
esac
