#!/bin/bash
cd ~/Documents/JeeLabs/Supplies

usage() {
cat <<'EOF'
JeeLabs Lab Supplies
Usage:
  labby <text> - find the specified search text (case insensitive)
  labby w <id> - open web page for specified product id
  labby a <box> <id> - add information about an item to the specified box
EOF
}

openPage() {
  case "$1" in
    DK-*) s="http://www.digikey.nl/product-search/en?keywords=${1#DK-}" ;;
    EB-*) s="http://www.ebay.com/itm/$1" ;;
    FL-*) s="http://nl.farnell.com/jsp/search/productdetail.jsp?SKU=${1#FL-}" ;;
    MR-*) s="http://nl.mouser.com/ProductDetail/${1#MR-}" ;;
    # use DigiKey if there is no supplier prefix
    *)    s="http://www.digikey.nl/product-search/en?keywords=$1" ;;
  esac
  open $s  # opens a web browser window on Mac OSX, since $s is a URL
}

addItem() {
  case "$1" in
    "") echo "Usage: labby a <box> <supplier-partid> ?<optional-notes>?"
        return ;;
  esac
  if [ ! -f data/$1 ]; then
    echo "'$1' is not an existing box, you need to create it first as 'data/$1'"
    return
  fi
  case "$2" in
    DK-*) ;;
    *) echo "Please specify a supplier and part id, e.g. 'DK-1N5239BFSCT-ND'"
       return ;;
  esac
  echo "whoops, this feature is not working yet..."
}

case "$1" in
  "") usage ;;
  w)  openPage $2 ;;
  a)  addItem $2 $3 ;;
  *)  cd ./data; grep -i "$*" * | sed -e "s/	/  /g" -e "s/:/	/" ;;
esac